export const testRusume = [
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27asd543ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d53143ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912d341f021479f27d543ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d51243ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d4543ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d2543ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d5143ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d5543ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d5413ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d5443ce',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d543ce1',
    __v: 0
  },
  {
    user_id: 'test_user_id',
    avatar: 'avatar',
    user_name: 'Evil Martian',
    resume_name: 'Фронтенд-разработчик к марсианам (React, PostCSS)',
    qualification: 'qualification',
    skills:
      'React • Node.js • JavaScript • HTML • CSS • PostCSS • Адаптивная верстка • БЭМ • Webpack',
    salary: 'от 4000 до 6000 $',
    town: 'town',
    busyness: 'Полный рабочий день',
    office_remote: 'Можно удалённо',
    experience: 'experience',
    description: 'description',
    contacts: 'contacts',
    date: '17 октября 2022 г.',
    _id: '634c912df021479f27d543ce3',
    __v: 0
  }
];
